const meals = ["breakfast", "lunch", "dinner", "snack"];
const mealLabels = { breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", snack: "Snack" };

// --- PDF Export (via print) ---

export function exportMealPlanPDF(plan, goalLabel) {
  const win = window.open("", "_blank");
  if (!win) return;

  const rows = plan.map(day => {
    const mealRows = meals
      .filter(m => day[m])
      .map(m => {
        const meal = day[m];
        const name = typeof meal === "object" ? meal.name : meal;
        const cals = typeof meal === "object" && meal.calories ? `${meal.calories} cal` : "";
        const macros = typeof meal === "object"
          ? [
              meal.protein != null ? `P: ${meal.protein}g` : "",
              meal.carbs != null ? `C: ${meal.carbs}g` : "",
              meal.fat != null ? `F: ${meal.fat}g` : "",
            ].filter(Boolean).join(" · ")
          : "";
        return `<tr>
          <td style="padding:8px 12px;font-weight:600;color:#6b7280;text-transform:uppercase;font-size:11px;letter-spacing:0.5px;vertical-align:top;width:80px">${mealLabels[m]}</td>
          <td style="padding:8px 12px">${name}</td>
          <td style="padding:8px 12px;text-align:right;white-space:nowrap;color:#6b7280;font-size:13px">${cals}${macros ? `<br><span style="font-size:11px">${macros}</span>` : ""}</td>
        </tr>`;
      })
      .join("");

    return `<div style="page-break-inside:avoid;margin-bottom:16px">
      <div style="display:flex;justify-content:space-between;align-items:baseline;padding:10px 12px;background:#f0fdf4;border-radius:8px 8px 0 0;border:1px solid #e5e7eb;border-bottom:none">
        <strong style="font-size:15px">${day.day}</strong>
        <span style="font-size:13px;color:#6b7280">${day.totalCalories || "—"} cal · P: ${day.totalProtein || "—"}g · C: ${day.totalCarbs || "—"}g · F: ${day.totalFat || "—"}g</span>
      </div>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:0 0 8px 8px;font-size:14px">${mealRows}</table>
    </div>`;
  }).join("");

  win.document.write(`<!DOCTYPE html><html><head><title>Meal Plan - ${goalLabel}</title>
    <style>
      body{font-family:-apple-system,system-ui,sans-serif;max-width:800px;margin:0 auto;padding:24px;color:#1a1a1a}
      table tr:not(:last-child) td{border-bottom:1px solid #f3f4f6}
      @media print{body{padding:0}div{page-break-inside:avoid}}
    </style></head><body>
    <h1 style="font-size:24px;margin:0 0 4px">${goalLabel} Meal Plan</h1>
    <p style="color:#6b7280;margin:0 0 20px;font-size:14px">Generated by Nourishi</p>
    ${rows}
  </body></html>`);

  win.document.close();
  setTimeout(() => win.print(), 300);
}

// --- iCal Export ---

function pad(n) { return String(n).padStart(2, "0"); }

function formatICSDate(date) {
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
}

function formatICSDateTime(date) {
  return `${formatICSDate(date)}T${pad(date.getHours())}${pad(date.getMinutes())}00`;
}

function escapeICS(str) {
  return str.replace(/[\\;,]/g, c => "\\" + c).replace(/\n/g, "\\n");
}

const mealTimes = {
  breakfast: { start: 7, end: 8 },
  lunch: { start: 12, end: 13 },
  dinner: { start: 18, end: 19 },
  snack: { start: 15, end: 15, endMin: 30 },
};

export function exportMealPlanICS(plan, goalLabel) {
  const now = new Date();
  // Start from next Monday
  const startDate = new Date(now);
  const dayOfWeek = startDate.getDay();
  const daysUntilMonday = dayOfWeek === 0 ? 1 : dayOfWeek === 1 ? 0 : 8 - dayOfWeek;
  startDate.setDate(startDate.getDate() + daysUntilMonday);

  let events = "";

  plan.forEach((day, dayIndex) => {
    const date = new Date(startDate);
    date.setDate(date.getDate() + dayIndex);

    meals.forEach(mealKey => {
      const meal = day[mealKey];
      if (!meal) return;

      const name = typeof meal === "object" ? meal.name : meal;
      const times = mealTimes[mealKey];

      const start = new Date(date);
      start.setHours(times.start, 0, 0);
      const end = new Date(date);
      end.setHours(times.end, times.endMin || 0, 0);

      let description = `${mealLabels[mealKey]} - ${goalLabel} Plan`;
      if (typeof meal === "object") {
        if (meal.calories) description += `\\nCalories: ${meal.calories}`;
        if (meal.protein != null) description += `\\nProtein: ${meal.protein}g`;
        if (meal.carbs != null) description += `\\nCarbs: ${meal.carbs}g`;
        if (meal.fat != null) description += `\\nFat: ${meal.fat}g`;
      }

      events += `BEGIN:VEVENT
DTSTART:${formatICSDateTime(start)}
DTEND:${formatICSDateTime(end)}
SUMMARY:${escapeICS(`${mealLabels[mealKey]}: ${name}`)}
DESCRIPTION:${description}
STATUS:CONFIRMED
END:VEVENT
`;
    });
  });

  const ics = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Nourishi//Meal Plan//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:${escapeICS(goalLabel)} Meal Plan
${events}END:VCALENDAR`;

  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `nourishi-meal-plan.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
